services:
  - type: web
    name: tchaller-backend
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"
    startCommand: gunicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --timeout 120 --max-requests 1000 --max-requests-jitter 100
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tchaller-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: "*"
      - key: CORS_ALLOW_CREDENTIALS
        value: "true"
      - key: CORS_ALLOW_METHODS
        value: "*"
      - key: CORS_ALLOW_HEADERS
        value: "*"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: PYTHONUNBUFFERED
        value: "1"

databases:
  - name: tchaller-db
    plan: free